### ISSUE TITLE
Doesn't seem to build with python v3.13.2 on Mac

### ISSUE THREAD

**Issue by baraknaveh** [JoshData/fast_diff_match_patch#30]
I'm getting:

```
        opt = self._enforce_underscore(opt, section)
      In file included from interface.cpp:4:
      ./diff-match-patch-cpp-stl/diff_match_patch.h:26:10: fatal error: 'limits' file not found
         26 | #include <limits>
            |          ^~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang++' failed with exit code 1
```

More info:

```
» clang++ --version
Apple clang version 16.0.0 (clang-1600.0.26.4)
Target: arm64-apple-darwin24.5.0
```

Happy to provide any additional info that could help!

Thanks!

**Comment by JoshData** [comment]
Every C++ compiler should have the 'limits' header. I'm not sure how that would fail.
